<?php
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;
?>
<ul class="<?php echo $this->navigation()->menu()->getUlClass(); ?>">
    <li class="text-right"><a href="#" id="nav-close">X</a></li>

    <?php foreach ($container as $page) { ?>
    <?php if (!$this->navigation()->accept($page)) continue; ?>
    <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
    <?php $hasChildren = $page->hasPages() ?>
    <?php if (!$hasChildren) { ?>
        <li<?php if ($page->isActive()) echo ' class="active"' ?>>
            <a
                href="<?php echo $page->getHref() ?>"
                <?php if ($page->getTarget() != ""): ?>
                    target="<?php echo $page->getTarget(); ?>"
                <?php endif; ?>
                >
                <?php if ($page->get("icon") !== ""): ?>
                    <span class="<?php echo $page->get("icon"); ?>"></span>
                <?php endif; ?>
                <?php echo $page->getLabel() ?>
            </a>
        </li>
    <?php } else { ?>
            <?php
            //check if access is allowed at least one item
            $access = false;
            foreach ($page->getPages() as $child) {
                if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
                    $access = true;
                }
            }
            if ($access) :
            ?>
            <li class="<?php if ($page->isActive(true)) echo ' active' ?>">
                <a href="#">
                    <?php echo $page->getLabel() ?>
                </a>
                <ul class="list-unstyled">
                    <?php foreach ($page->getPages() as $child): ?>
                        <?php if (!$this->navigation()->accept($child)) continue; ?>
                        <?php if ($child->get("separator") === true): ?>
                            <li class="divider"></li>
                            <?php
                            continue;
                        endif;
                        ?>
                        <li class="sub-nav <?php if ($child->isActive()) echo ' active' ?>">
                            <a
                                href="<?php echo $child->getHref() ?>"
                                <?php if ($child->getTarget() != ""): ?>
                                    target="<?php echo $child->getTarget(); ?>"
                                <?php endif; ?> >
                                <?php if ($child->get("icon") !== ""): ?>
                                    <span class="<?php echo $child->get("icon"); ?>"></span>
                                <?php endif; ?>
                                <?php echo $child->getLabel() ?>
                            </a>
                        </li>
                    <?php endforeach ?>
                </ul>
            </li>
            <?php endif; ?>
    <?php } ?>
    <?php } ?>
</ul>
<?php return ; ?>





